baseURL = 'https://katra.ballardini.com.ar/'
copyright = 'César Ballardini'
defaultContentLanguage = "es"
enableRobotsTXT = true
resourceDir = "./resources"
sectionPagesMenu = "main"
theme = "ananke"
#theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]
timeZone = 'America/Buenos_Aires'
title = 'katra'


[frontmatter]
  date = [':filename', ':default']

[languages.es]
contentDir = "content/es"
languageCode = 'es-AR'
weight = 1
title = "katra"
read_more_copy = "Leer más..."

[languages.en]
contentDir = "content/en"
languageCode = 'en-US'
weight = 2
title = "katra.en"
read_more_copy = "Read more about this entry"

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[services.googleAnalytics]
id = ''

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"



[params]
author = "César Ballardini"
date_format = "02 de January de 2006"
favicon = ""
recent_posts_number = 3
show_reading_time = true
site_logo = ""
text_color = ""

# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"

# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"

# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"

[params.ananke.social.share]
networks = [
  "email",
  "linkedin",
  "x-twitter",
  "github",
]

[params.ananke.social.follow]
networks = [
  "linkedin",
  "x-twitter",
  "github",
]

[params.ananke.social.email]
username = "cesar.ballardini@gmail.com"

[params.ananke.social.linkedin]
username = "cesarballardini"

[params.ananke.social.x-twitter]
username = "cesarballardini"
# https://x.com/cesarballardini

[params.ananke.social.github]
username = "CesarBallardini"
# https://github.com/CesarBallardini

[params.ananke.social.facebook]
username = "cesar.ballardini"
# profilelink = "https://www.facebook.com/cesar.ballardini"

