blank_issues_enabled: false
contact_links:
  - name: Feature requests and problem solutions
    url: https://github.com/theNewDynamic/gohugo-theme-ananke/discussions
    about: Please ask and answer questions here. Open a bug report only if you are sure it is a bug.
